// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDJRXx-N0_r-gKIjdITQs8-vkVWJ99VLCw',
    appId: '1:429010695618:web:124de1dc839ed238bd125b',
    messagingSenderId: '429010695618',
    projectId: 'datevibe-8ed5a',
    authDomain: 'datevibe-8ed5a.firebaseapp.com',
    storageBucket: 'datevibe-8ed5a.firebasestorage.app',
    measurementId: 'G-W4T59XKSLK',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCFfjzXwnW2ma9VI-o4RogYoajKMrZfSVY',
    appId: '1:429010695618:android:19363f74985e85c4bd125b',
    messagingSenderId: '429010695618',
    projectId: 'datevibe-8ed5a',
    storageBucket: 'datevibe-8ed5a.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB10g5H4CftOfhNmlr38UlxQ9qCAn1W_Qg',
    appId: '1:429010695618:ios:2df4ab62cd7d00a0bd125b',
    messagingSenderId: '429010695618',
    projectId: 'datevibe-8ed5a',
    storageBucket: 'datevibe-8ed5a.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB10g5H4CftOfhNmlr38UlxQ9qCAn1W_Qg',
    appId: '1:429010695618:ios:2df4ab62cd7d00a0bd125b',
    messagingSenderId: '429010695618',
    projectId: 'datevibe-8ed5a',
    storageBucket: 'datevibe-8ed5a.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDJRXx-N0_r-gKIjdITQs8-vkVWJ99VLCw',
    appId: '1:429010695618:web:5390260391c19a17bd125b',
    messagingSenderId: '429010695618',
    projectId: 'datevibe-8ed5a',
    authDomain: 'datevibe-8ed5a.firebaseapp.com',
    storageBucket: 'datevibe-8ed5a.firebasestorage.app',
    measurementId: 'G-HEBQTM70S0',
  );
}
